### ISSUE TITLE
Changing directions too quickly kills you.

### ISSUE THREAD

**Issue by vishvananda** [patmood/vim_snake#2]
I believe this is a bug because it makes quick movement very difficult.

If you are moving right and you press h for left then the keystroke is ignored. If, on the other hand, you press j to move down, and then quickly press h before the snake has started moving down, you end up killing yourself.

I think there needs to be a keymove buffer and only one movement command should be executed for each frame that the snake moves.

**Comment by patmood** [comment]
@vishvananda 7 years later and I've fixed this haha. Rewrote the project to play around with Go and web assembly!
